@startuml
class Солнце
{
   расположение
}

class Облако
{
   позиция
}

class Снимок
{
   расширение
}
class Камера
class Система
{
   время
   погода
}

class Генератор
{
   вкл/выкл
}


Снимок -- Камера : делает <
Снимок -- Система: получает снимок <
Солнце -- Снимок : на снимке <
Снимок - Облако: на снимке 2 >
Камера - Система : контроль <
Система - Генератор : переключает >
@enduml
