@startuml
control "Система" as pc
entity "Генератор" as generator
actor "Пользователь" as user
database "  Память" as cloudStorage

(Получить снимок) <- pc
(Определить время) <-- pc
(Определить какая погода) <-- pc
(Определить расположение солнца и облака) <-- pc
pc -> (рассчитать скорость и направление облака)
pc --> (Включить/выключить генератор)
pc --> (Выгрузить данные в память)
pc --> (Рассчитать время пока не видно солнца)

(Включить/выключить генератор) --> Генератор

(Выгрузить данные в память) --> Память
Память <-> Пользователь : обмен данными
@enduml
